### PR TITLE
Save datasets using clojure/data.csv

### PR DESCRIPTION
**Pull request by rbuchmann**
This pull request addresses #341, it changes saving data-sets to use org.clojure/data.csv, like @mikera suggested. Let me know if you are missing anything.

### CODE REVIEW

**Comment by mikera** [comment]
Looks sensible. Any chance of a test that serialises a small dataset to a byte array, sets it back and confirms it is equal to the original?

**Comment by rbuchmann** [comment]
Sure, probably a good idea. I'll add it.

**Comment by alexott** [comment]
Thank you! 

I manually merged it into develop branch

**Comment by rbuchmann** [comment]
Oh, thanks, had completely forgotten about this one. Thank you for merging.

**Pull request closed without merging**
