### PR TITLE
Fix $rollup for clojure.core.matrix.dataset

### PR DESCRIPTION
**Pull request by keytiong**
# Summary

`$rollup` in 1.9.1-SNAPSHOT fails with the `ArityException` when passing in a `clojure.core.matrix.dataset`

`ArityException Wrong number of args (2) passed to: core/col-names  clojure.lang.AFn.throwArity (AFn.java:429)`
# Reproduction Steps

```
(require '[incanter.core :as i])
(def data (i/to-dataset [{:sex "Male" :height 1.5} {:sex "Male" :height 1.7}]))
(i/$rollup :mean :sex :height data)
```

### CODE REVIEW

**Comment by arichiardi** [comment]
Do we need some help on this one?

**Comment by mikera** [comment]
Looks like there are conflicts?

**Comment by dgtized** [comment]
Haven't had a chance to verify this fix works, but pretty certain I ran into this error locally.

**Comment by mikera** [comment]
Fix looks good to me, thanks!

**Pull request merged**
