### PR TITLE
Fix matrix correlation, covariance and PCA calculations

### PR DESCRIPTION
**Pull request by nblumoe**
- Fix correlation calculations for matrices.
- Make covariance calculate covariance on the data columns instead of rows, compliant with R.
- Make PCA use covariance instead of correlation, compliant with R.

### CODE REVIEW

**Comment by mikera** [comment]
Hi @nblumoe can you comment on why you think that covariance should use columns rather than rows?

We wouldn't want to make a breaking change for no reason, plus I've always found it to be more convenient to calculate by rows (by analogy with a vector-of-vectors)

**Comment by nblumoe** [comment]
Hi @mikera. I find it very odd to use rows tbh. I usually need it for columns (variables, dimensions) rather than rows (samples). However, this might be different in other domains and then it simply comes down to what one needs the most to prevent having to transpose the matrix first.

Nevertheless, I checked implementations from R, Matlab and Mathematica. They all use columns when providing a matrix as the argument:
http://de.mathworks.com/help/matlab/ref/cov.html
http://reference.wolfram.com/language/ref/Covariance.html
http://stat.ethz.ch/R-manual/R-patched/library/stats/html/cor.html

May I ask why you find rows more convenient? Is it due to the domain of the data you are usually working with?

As a breaking change, this could also be part of the v2 release, if we merge it like this.

**Comment by mikera** [comment]
Ah... perhaps we actually mean the same thing.....

Just to be clear I expect that given:
- A is a NxM matrix with N rows (samples) and M columns (random variables)

Then `(covariance A)` should return an MxM matrix representing the covariance between the M random variables across all of the samples.

Doesn't help that the source uses `n` and `m` differently in different places....

**Comment by nblumoe** [comment]
I understand. What you described is also how I would want it to behave. This can be a bit confusing.

As a sanity check, could you please have a look at the following code. It shows the old implementation on the develop branch and after that my fixed version.

### Current develop (2c73b0054b934787ab07d5447782a55f3d4673c0)

```clojure
user> (def dat [[1 2 1 4][2 4 (+ 1 1E-12) 3][3 6 1 2]])                                    
#'user/dat                                                                                 

user> (incanter.core/to-dataset dat)                                                                                           
| 0 | 1 |              2 | 3 |                                                             
|---+---+----------------+---|                                                             
| 1 | 2 |              1 | 4 |                                                             
| 2 | 4 | 1.000000000001 | 3 |                                                             
| 3 | 6 |              1 | 2 |                                                             

user> (incanter.core/to-dataset (correlation dat))                                         
|                  0 |                   1 |                      2 |                   3 |
|--------------------+---------------------+------------------------+---------------------|
| 0.6507913734560759 | 0.32539568672792935 | -4.816823780255761E-17 | 0.32539568672792935 |
| 0.5423261445464044 |  0.7592566023652046 |                    0.0 |  0.7592566023652046 |

user> (incanter.core/to-dataset (covariance dat))                                          
|                  0 |                  1 |                       2 |                  3 | 
|--------------------+--------------------+-------------------------+--------------------| 
| 2.0000000000000004 | 0.9999999999996666 | -1.4802973661668753E-16 | 0.9999999999996666 | 
| 1.6666666666656667 | 2.3333333333326665 |                     0.0 | 2.3333333333326665 | 
```
### Fixed implementation (caee4dc4a3e154ee9df5184110cd2ae90016c64b)
```clojure
user>  (def dat [[1 2 1 4][2 4 (+ 1 1E-12) 3][3 6 1 2]])                                           
#'user/dat                                                                                         

user> (incanter.core/to-dataset dat)                                                               
| 0 | 1 |              2 | 3 |                                                                     
|---+---+----------------+---|                                                                     
| 1 | 2 |              1 | 4 |                                                                     
| 2 | 4 | 1.000000000001 | 3 |                                                                     
| 3 | 6 |              1 | 2 |                                                                     

user> (incanter.core/to-dataset (correlation dat))                                                 
|                   0 |                   1 |                  2 |                    3 |          
|---------------------+---------------------+--------------------+----------------------|          
|                 1.0 |                 1.0 |                0.0 |                 -1.0 |          
|                 1.0 |                 1.0 |                0.0 |                 -1.0 |          
| 9.61395862690663E-5 | 9.61395862690663E-5 | 0.9999444691371517 | -9.61395862690663E-5 |          
|                -1.0 |                -1.0 |                0.0 |                  1.0 |          

user> (incanter.core/to-dataset (covariance dat))                                                  
|                     0 |                      1 |                     2 |                      3 |
|-----------------------+------------------------+-----------------------+------------------------|
|                   1.0 |                    2.0 |                   0.0 |                   -1.0 |
|                   2.0 |                    4.0 |                   0.0 |                   -2.0 |
| 5.551115123125783E-17 | 1.1102230246251565E-16 | 3.333740976605969E-25 | -5.551115123125783E-17 |
|                  -1.0 |                   -2.0 |                   0.0 |                    1.0 |
```

Only now do I realize, that it would have been smarter not using a square matrix. However, a NxM matrix results in a MxM covariance/correlation matrix, I checked that too.

**Comment by mikera** [comment]
New results look reasonably sane. 

The only think that strikes me as a bit odd is that the correlation / covariance matrices aren't symmetric. I guess this can be attributed to numerical errors?

**Comment by nblumoe** [comment]
Yes, I would say it's just numerical errors.

Here is another example:

```clojure
(def dat [[18 2 41 34][2 41 0.1 3][3 61 12 2]]) 
(def result  (incanter.stats/correlation dat))
(incanter.core/to-dataset (incanter.core/minus result (incanter.core/trans result)))

|                      0 |                      1 |                       2 |                       3 |
|------------------------|------------------------|-------------------------|-------------------------|
|                    0.0 |                    0.0 |   2.220446049250313E-16 |                     0.0 |
|                    0.0 |                    0.0 | -1.1102230246251565E-16 |                     0.0 |
| -2.220446049250313E-16 | 1.1102230246251565E-16 |                     0.0 | -1.1102230246251565E-16 |
|                    0.0 |                    0.0 |  1.1102230246251565E-16 |                     0.0 |

```

How could we test if it's numerical errors only? Having property based tests might be a good idea for this (also for Incanter in general). Other ideas?

**Comment by mikera** [comment]
Well there is an arity override for `equals` that allows you to provide the precision. So you can test for stuff like:

`(is (equals M (transpose M) PRECISION))`

Agree that property based testing is a good idea in general. I've started to add some custom property based tests and generators to the library : https://github.com/mikera/core.matrix.testing

Some of this may be equally useful for Incanter?

**Comment by mikera** [comment]
Merging this because it seems to be a clear improvement

**Pull request merged**
