### PR TITLE
Use list-of-lists when creating table from dataset

### LINKED ISSUE #287: `view` is broken for datasets on v1.9.0
For example `(view (get-dataset :iris))` fails with `IllegalArgumentException No matching ctor found for class java.util.Vector`.

`view` still works for list and matrices though.

To reproduce, see below:

```
$ cat project.clj
(defproject test-incanter "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [incanter "1.9.0"]])

$ lein repl
nREPL server started on port 50388 on host 127.0.0.1 - nrepl://127.0.0.1:50388
REPL-y 0.3.5, nREPL 0.2.6
Clojure 1.6.0
Java HotSpot(TM) 64-Bit Server VM 1.7.0_60-b19
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=>  (use '(incanter core stats datasets charts))
nil
user=>   (view (sample-normal 100))
#<JFrame javax.swing.JFrame[frame0,0,23,400x600,invalid,layout=java.awt.BorderLayout,title=Incanter Matrix,resizable,normal,defaultCloseOperation=HIDE_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,22,400x578,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]>
user=>   (view (get-dataset :iris))

IllegalArgumentException No matching ctor found for class java.util.Vector  clojure.lang.Reflector.invokeConstructor (Reflector.java:183)
```

### PR DESCRIPTION
**Pull request by nblumoe**
Before this change, rows were SliceWrappers, this made the Vector
constructor fail.

fixes #287

### CODE REVIEW

**Comment by nblumoe** [comment]
Pretty minor change and not expected to have far reaching implications. A review as a sanity check if very appreciated though!

**Comment by Gerrrr** [comment]
Thank you for the catch!
Can you please also add the test for this case?

**Comment by mikera** [comment]
it seems a bit odd to be using java.util.Vector. Shouldn't this be clojure.core/vec instead? Or even better use the corresponding core.matrix functions?

**Comment by Gerrrr** [comment]
I tried it out and it resulted in 
```
IllegalArgumentException No matching ctor found for class javax.swing.JTable  clojure.lang.Reflector.invokeConstructor (Reflector.java:183)
```

I guess `javax.swing.JTable` does not accept `clojure.lang.PersistentVector` as parameters.

**Comment by nblumoe** [comment]
@mikera well yeah, good point about the test. Just skipped it because there are not tests at all for `view` at the moment. Not a good excuse admittedly, but rather yet another incentive. ;)
Which `core.matrix` functions are you referring to? Would like to check it out and see how to improve it.

@Gerrrr from your comment I understood, that there is no further reason to look into usage of `clojure.lang.PersistentVector` right?

**Comment by Gerrrr** [comment]
@nblumoe, yeah, I will merge PR. Thank you again!
If you can also add the test case for this, it would be great. Otherwise I will add it myself.

**Comment by nblumoe** [comment]
@Gerrrr I am going to add it

**Comment by nblumoe** [comment]
While writing the test I realized we have some redundant code. Check this commit out: https://github.com/nblumoe/incanter/commit/42214c67a31465c7f5eea11dbec3c49fa6bd1a15#diff-06e894184b0bdeba0a173f87ae72e5aeR2365

`data-table` creates a `JTable`  from a dataset and the `view` multimethod dispatches to `JTable` via `defmethod view javax.swing.JTable`.

Combining those existing functions results in a working `view` multimethod for datasets like this:
` ` `
(defmethod view ::dataset
  ([obj & options]
   (view (data-table obj))))
` ` `

This is my suggested solution. This also allows to test the actual issue (type conflicts with the ` java.util.Vector`  constructor) in a more sane way, as the test only needs to test `data-table` which does not render anything.

Will send an updated merge requests and open a related issue about how to improve test coverage for `view`  in general.

**Comment by nblumoe** [comment]
Here is an issue to discuss testing approach for the `view` function: https://github.com/incanter/incanter/issues/291

**Comment by mikera** [comment]
I'm not analysed this at all, but I think a few things in this area can be simplified. `incanter.core.charts` doesn't seem to be using `core.matrix` functions where it could... in particular `m/slices` is a better way for getting a list of rows, `m/to-nested-vectors` is a better way to convert something into a Clojure vector-of-vectors, and `m/transpose` seems like it could be handy in many places :-)

For performance when using an accelerated implementation, it is always going to be better to use `core.matrix` API calls for the processing, and only convert to a specific format at the end for iterop purposes (e.g. `(mapv #(java.util.Vector. (m/eseq %)) (m/slices M))` or something like that

**Comment by mikera** [comment]
Of course still think the patch looks good - just sharing ideas for future improvements

**Comment by nblumoe** [comment]
Updated the test. Especially I removed the test for `view` itself. As I expressed in the corresponding issue  https://github.com/incanter/incanter/issues/291 this should not be part of Incanter's unit tests.

Hope it can be merged now after your review.

**Comment by nblumoe** [comment]
Had to rerun Travis CI, there was an issue pulling dependencies, but not failing tests.

**Comment by mikera** [comment]
Looks good to me. @Gerrrr are you OK to merge?

**Comment by Gerrrr** [comment]
Yes, also looks for good for me.

**Comment by mikera** [comment]
Cool - thanks all!

**Pull request merged**
