### PR TITLE
Fix broken links in README

### PR DESCRIPTION
**Pull request by sesm**
work

### CODE REVIEW

**Comment by sesm** [comment]
CI fails with a weird error
`The command "sh -e /etc/init.d/xvfb start" failed and exited with 127 during .` 
Opening/closing PR to restart the build doesn't help.
Any ideas what might be happening there?

**Comment by sesm** [comment]
CI issue is fixed here https://github.com/incanter/incanter/pull/408

**Comment by roachmd** [comment]
@sesm , I'm guessing xvfb cannot be found. Might need to update the before_install

```language: clojure
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libgfortran3
 - sudo apt-get install xvfb
install: lein modules install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: lein modules test```

**Comment by sesm** [comment]
@roachmd from what I've found on the internet, in newer versions of travis we should launch `xvfb` like this 
```
services:
 - xvfb
```
(as opposed to launching it manually)
Please see: https://github.com/incanter/incanter/pull/408

**Pull request merged**
